### ISSUE TITLE
Multiple windows using display

### ISSUE THREAD

**Issue by eitanlees** [altair-viz/altair_viewer#20]
I was giving the new package a try and was unsure about some behavior.

When running in an Ipython session each call to `display` opened up a new window/tab. Is that expected? I was thinking subsequent calls would just refresh the window rather than open a new tab. 

![altair-viewer-ipython](https://user-images.githubusercontent.com/2041969/71690222-13cdd680-2d72-11ea-88ad-a381a885ef00.gif)

``` python 
import altair as alt
from vega_datasets import data
import altair_viewer

source = data.iris()

chart = alt.Chart(source).mark_circle().encode(
    alt.X('sepalLength', scale=alt.Scale(zero=False)),
    alt.Y('sepalWidth', scale=alt.Scale(zero=False, padding=1)),
    color='species',
    size='petalWidth'
)

altair_viewer.display(chart)
altair_viewer.display(chart)
```

**Comment by jakevdp** [comment]
Yes, unfortunately this is expected (though not intended).

The package calls ``webbrowser.open`` with ``new=0``, which will avoid opening the new window in supported environments, though not all OS/browser combinations are supported (see https://docs.python.org/3/library/webbrowser.html#webbrowser.open).

If you're working in the notebook, I'd suggest using the ``altair_viewer`` renderer instead. When that is enabled, you can call ``chart.display()`` to display the chart, and it will not attempt to open a new browser window.

**Comment by jakevdp** [comment]
I had thought of setting up some socketIO communication so that the runtime can detect when the browser window is closed, but I haven't dug-in on it yet (and I'd be a bit worried about brittleness in practice).

**Comment by jakevdp** [comment]
#21 should fix this issue
