### ISSUE TITLE
Custom hostname/port of ChartViewer?

### ISSUE THREAD

**Issue by grwlf** [altair-viz/altair_viewer#37]
Hello. I run Altair from Docker container, and I would like to see a plot with my Host machine's browser. In order to do it I execute a code like below:
```python
df=... # my data
alt.Chart(df).mark_line().encode(x='step', y='value').show()
```

The code prints a notice like  `Displaying chart at http://localhost:15169/`.

Unfortunately, if I open the browser and point it to `172.17.0.4:15169` (It happens to be my container's ip) I only see Altair favicon but no plots. This is because HTML contains urls that refer to server as to `localhost`, which has meaning only inside the container. Is it possible to explicitly specify the IP to bind to?

(There is a workaround - to create custom viewer with `viewer=ChartViewer(use_bundled_js=False)` and use it, but I would still like to get scripts installed on my container machine.)

**Comment by grwlf** [comment]
Note, complete workarouns is
```python
import altair_viewer
v=altair_viewer.ChartViewer(False)
altair_viewer.display = v.display
altair_viewer.render = v.render
altair_viewer.show = v.show
```

**Comment by jakevdp** [comment]
No, there's currently no way to configure this: it's hard-coded here: https://github.com/altair-viz/altair_data_server/blob/32d00253acf98977a97cf4cae048946347eac280/altair_data_server/_provide.py#L181

I would be open to contributions that make this configurable.

**Comment by grwlf** [comment]
I think I'll go with a workaround for now. Thanks for explanation!

**Comment by jakevdp** [comment]
OK. In that case, this workaround is a bit cleaner:
```
import altair_viewer
altair_viewer._global_viewer._use_bundled_js = False
```

**Comment by jakevdp** [comment]
It would be worth adding a hook to adjust that setting.

**Comment by Nitujhs** [comment]
Hi. I have been working to see my plot in my organization server edge node in similar way. But, same issue happens to me. I am seeing a workaround above. But is it something just to see my plot at once or it can be utilized to share link with other viewers also?
Also, am not very clear on how you guys are creating a viewer and how to embed this in my running code?

**Comment by Nitujhs** [comment]
@jakevdp need your assistance here

**Comment by Nitujhs** [comment]
@jakevdp need your assistance here

**Comment by germank** [comment]
Hi,
I would like to point that there's another reason for setting a custom port other than the broken link mentioned above, namely, when you are running altair on a remote host and use an ssh tunnel to connect to the web host to view the plot. In the way things stand now, you need to create a new tunnel every time you get a new port, which is cumbersome. Allowing the user to set a custom port would simplify things for this use case.

**Comment by iliatimofeev** [comment]
Ugly hack

```python
def init_offline_altair(server_name:str, port_number:int = None)->None:
    import altair_viewer

    class EventProviderMock(altair_viewer._event_provider.EventProvider):
        @property
        def url(self) -> str:
            return f"http://{server_name}:{self.port}"

        def start(
            self, port=None, timeout=1, daemon = True
        ):
            return super().start(port = port_number, timeout=timeout, daemon=daemon)

    altair_viewer._viewer.EventProvider = EventProviderMock

# call it before first render
init_offline_altair("myserver",9999)

```

**Comment by iliatimofeev** [comment]
A bit more ugly hack.
 Works if you serve notebook from docker and use big dataset
```python
def init_offline_altair(server_name:str,port_number:int = None)->None:
    import altair_viewer
    import altair_data_server
    import altair

    class EventProviderMock(altair_viewer._event_provider.EventProvider):
        @property
        def url(self) -> str:
            return f"http://{server_name}:{self.port}"
        def start(
            self, port=None, timeout=1, daemon = True
        ):
            return super().start(port = port_number, timeout=timeout, daemon=daemon)


    altair_viewer._viewer.EventProvider = EventProviderMock
    altair.renderers.enable('altair_viewer',inline=True)
    altair_viewer._global_viewer._initialize()
    altair_data_server.data_server._provider = altair_viewer._global_viewer._provider
    alt.data_transformers.enable('data_server')
```
do not forget to publish additional port for container

**Comment by joelostblom** [comment]
Since Altair 5.3, the functionality of Altair Viewer is now available in Altair via the [vl-convert](https://github.com/vega/vl-convert) package instead. See [the docs on how to use the browser renderer](https://altair-viz.github.io/user_guide/display_frontends.html#browser-renderer) to display charts via `.show()`, and the PR https://github.com/altair-viz/altair/pull/3379 for more details.

We are going to archive this repo, so I'm closing all the open issues and PRs before doing so. Try out the new options for rendering charts mentioned above and if you run into issues, please open an issue directly in the altair or vl-convert repo.
