### ISSUE TITLE
Update entrypoint to Vega-Lite 5 so Altair v5 chart renders

### ISSUE THREAD

**Issue by indigoviolet** [altair-viz/altair_viewer#52]
I recently had to update altair to master to address an unrelated issue, and found that `altair_viewer`'s registration no longer worked. Might need to update the entrypoints to something like

https://github.com/vega/ipyvega/blob/e7fb07ce599f78117b94bcaeddd8dc56e5554a38/pyproject.toml#L40

**Comment by indigoviolet** [comment]
workaround is something like `alt.renderers.register('altair_viewer', altair_viewer._viewer.ChartViewer().render)`

**Comment by joelostblom** [comment]
Yes, there will need to be a new release of altair_viewer that matches the version of vega-lite used in the new version of altair before it works out of the box again

**Comment by mattijn** [comment]
@indigoviolet I have one question. You mention you found a workaround. Can you provide a small complete code snippet how you apply this? I'm wondering how that could work.

**Comment by joelostblom** [comment]
I think we can close this as https://github.com/altair-viz/altair_viewer/pull/54 was merged. There will be one more update when VL 5.7 is out and after that a new release of altair_viewer will be out.

**Comment by mattijn** [comment]
I think this can't be closed. It still requires a new entry point for Altair vl 5, around here:

https://github.com/altair-viz/altair_viewer/blob/master/setup.py#L74

**Comment by mattijn** [comment]
done per https://github.com/altair-viz/altair_viewer/pull/55

**Comment by franzhaas** [comment]
This now affects the released version of altair 5.0.1 as well as 5.0.0.
